// Auto-generated by scripts/sync-env.mjs. Do not edit manually.
export const firebaseConfig = {
  apiKey: 'AIzaSyARV02NBn9amQKJ33PvDcHc8E_1H8A72A0',
  authDomain: 'riftbound-e9841.firebaseapp.com',
  databaseURL: 'https://riftbound-e9841-default-rtdb.europe-west1.firebasedatabase.app',
  projectId: 'riftbound-e9841',
  storageBucket: 'riftbound-e9841.firebasestorage.app',
  messagingSenderId: '870805166119',
  appId: '1:870805166119:web:c668d3053f3f85c60a1602',
  measurementId: 'G-95YLKE20ZX',
};
