import { config } from 'dotenv';
import { writeFileSync, existsSync, mkdirSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, resolve } from 'path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const rootDir = resolve(__dirname, '..');

config({ path: resolve(rootDir, '.env') });

const firebaseConfig = {
  apiKey: process.env.FIREBASE_API_KEY ?? '',
  authDomain: process.env.FIREBASE_AUTH_DOMAIN ?? '',
  databaseURL: process.env.FIREBASE_DB_URL ?? '',
  projectId: process.env.FIREBASE_PROJECT_ID ?? '',
  storageBucket: process.env.FIREBASE_STORAGE_BUCKET ?? '',
  messagingSenderId: process.env.FIREBASE_MESSAGING_SENDER_ID ?? '',
  appId: process.env.FIREBASE_APP_ID ?? '',
  measurementId: process.env.FIREBASE_MEASUREMENT_ID ?? '',
};

const missing = Object.entries(firebaseConfig)
  .filter(([, value]) => !value)
  .map(([key]) => key);

if (missing.length) {
  console.warn(
    `[sync-env] Missing Firebase fields in .env: ${missing.join(', ')}. Generated config may be incomplete.`
  );
}

const outputDir = resolve(rootDir, 'src/environments');
if (!existsSync(outputDir)) {
  mkdirSync(outputDir, { recursive: true });
}

const serialize = (value) => value.replace(/'/g, "\\'");

const content = `// Auto-generated by scripts/sync-env.mjs. Do not edit manually.\nexport const firebaseConfig = {\n  apiKey: '${serialize(firebaseConfig.apiKey)}',\n  authDomain: '${serialize(firebaseConfig.authDomain)}',\n  databaseURL: '${serialize(firebaseConfig.databaseURL)}',\n  projectId: '${serialize(firebaseConfig.projectId)}',\n  storageBucket: '${serialize(firebaseConfig.storageBucket)}',\n  messagingSenderId: '${serialize(firebaseConfig.messagingSenderId)}',\n  appId: '${serialize(firebaseConfig.appId)}',\n  measurementId: '${serialize(firebaseConfig.measurementId)}',\n};\n`;

writeFileSync(resolve(outputDir, 'firebase-config.ts'), content, { encoding: 'utf-8' });
console.log('[sync-env] Firebase config synced.');
